const express = require("express");
const app = express.Router();
const Auction = require("../app/controllers/auction.controller.js");
const Collection = require("../app/controllers/collection.controller.js");
const Item = require("../app/controllers/item.controller.js");
const Message = require("../app/controllers/message.controller.js");
const Putonsale = require("../app/controllers/putonsale.controller.js");
const Question = require("../app/controllers/question.controller.js");
const Review = require("../app/controllers/reviews.controller.js");
const Log = require("../app/controllers/trading.controller.js");
const User = require("../app/controllers/user.controller.js");

app.post("/addAuctionList", Auction.addAuctionList);
app.post("/cancelBid", Auction.cancelBid);
app.get("/getCollection", Collection.getCollectionByAddress);
app.post("/addCollection", Collection.addCollection);

app.get("/getItemAll", Item.getItemAll);
app.get("/getItem", Item.getItem);
app.post("/addItem", Item.addItem);
app.post("/togglefavor", Item.toggleFavor);
app.get("/isfavor", Item.isFavor);
app.get("/mywhishlist", Item.getFavorListByLiker);
app.get("/messages", Message.getMessages);
app.post("/addMessage", Message.addMessage);
app.get("/getPutonsaleAll", Putonsale.getPutonsaleAll);
app.get("/getputonsale", Putonsale.getPutonsale);
app.get("/getputonsalebymaker", Putonsale.getPutonsaleByMaker);
app.get("/getPutonlistAndAuctionlist", Putonsale.getPutonlist);
app.post("/putonsale", Putonsale.addPutonsale);
app.post("/cancelList", Putonsale.cancelList);
app.post("/updateputonsale", Putonsale.updatePutonSale);
app.get("/getPutonsalePerPage", Putonsale.getPutonsalePageNum);
// app.get("/getTopPutonsale", Putonsale.getTopPutonsale);
app.get("/questions", Question.getQuestions);
app.post("/add_questions", Question.addQuestion);
app.get("/my-questions", Question.getMyQuestion);
app.get("/reviews", Review.getReviews);
app.get("/getReviewsByMaker", Review.getReviewsByMaker);
app.post("/addReview", Review.addReview);
app.post("/feedbacks", Review.addFeedback);
app.get("/getLogs", Log.getLogs);
app.post("/addLog", Log.addLog);
app.post("/updateLog", Log.updateLog);
app.get("/userInfo", User.getUserInfo);
app.post("/register", User.RegisterUser);
app.get("/topUser", User.getTopUserList);

module.exports = app;
